/**
 * The rules page (/minpentai/rules) is Claude Design's "Minpentai in this edition · the rules"
 * (docs/design/minpentai-rules.dc.html), word for word. This writes its article into
 * src/app/minpentai/rules/rules-html.ts with the site's fonts and colour tokens in place of
 * Design's literal values (so it follows the theme), and "Under the hood" linked to the book's
 * rule page. Run after Design's file changes; `--check` fails if the committed file is stale.
 *
 *   npx tsx scripts/build-minpentai-rules.ts [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'src/app/minpentai/rules/rules-html.ts');

export function rulesHtml(): string {
  const src = readFileSync(path.join(ROOT, 'docs/design/minpentai-rules.dc.html'), 'utf8');
  const article = src.match(/<article[^>]*>([\s\S]*?)<\/article>/)?.[1];
  if (!article) throw new Error("Design's article was not found");
  return article
    .replace(/font-family:'DM Mono',monospace/g, 'font-family:var(--label)')
    .replace(/font-family:'Crimson Pro',serif/g, 'font-family:var(--reading)')
    .replace(/#1D1D1B/gi, 'var(--ink)')
    .replace(/#4A463F/gi, 'var(--body)')
    .replace(/#6A675F/gi, 'var(--muted)')
    .replace(/#DAD6CC/gi, 'var(--rule)')
    .replace(/#F4F2ED/gi, 'var(--paper)')
    .replace(/#B3306E/gi, 'var(--dzego)')
    .replace(/#2E5A3A/gi, 'var(--link)')
    .replace('stays in Under the hood', 'stays in <a href="/minpentai/rule">Under the hood</a>')
    .replace(/\s+/g, ' ')
    .trim();
}

const body = `/** GENERATED by scripts/build-minpentai-rules.ts from docs/design/minpentai-rules.dc.html. Do not edit. */\nexport const RULES_HTML = ${JSON.stringify(rulesHtml())};\n`;
if (process.argv.includes('--check')) {
  const now = readFileSync(OUT, 'utf8');
  if (now !== body) { console.error('src/app/minpentai/rules/rules-html.ts is stale: run npx tsx scripts/build-minpentai-rules.ts'); process.exit(1); }
  console.log('rules page: up to date with Design');
} else {
  writeFileSync(OUT, body);
  console.log(`wrote ${path.relative(ROOT, OUT)}`);
}
