/**
 * Records the four-player match the tutorial shows, so the page replays it instead of
 * running four computer players on the visitor's phone. Plays seeds 1–40 with
 * 'normal' computer players (src/lib/minpentai/ai.ts) and keeps the first whose
 * match ends with three players out, the first no earlier than turn 80, by turn 400.
 *
 *   npx tsx scripts/record-minpentai-match.ts   # writes src/lib/minpentai/watch-moves.ts
 */
import { writeFileSync } from 'node:fs';
import { plan, rng } from '../src/lib/minpentai/ai';
import { newMatch, place, placeProblem, runToIntervention, type Placement } from '../src/lib/minpentai/match';
import { WATCH_SETUP } from '../src/lib/minpentai/matches';

for (let seed = 1; seed <= 40; seed++) {
  let m = newMatch(WATCH_SETUP);
  const random = rng(seed);
  const moves: { turn: number; player: number; p: Placement }[] = [];
  while (m.winner === undefined) {
    // Everyone plans from the same moment, then all moves land together.
    const plans = m.players.map((p) => (p.out ? [] : plan(m, p.id, 'normal', random)));
    // A move another player's move has crowded out is dropped, as the page would.
    plans.forEach((list, player) => list.forEach((p) => {
      if (placeProblem(m, player, p)) return;
      moves.push({ turn: m.board.turn, player, p });
      m = place(m, player, p);
    }));
    m = runToIntervention(m);
  }
  const outs = m.events.filter((e) => e.kind === 'out').map((e) => e.turn);
  console.log(`seed ${seed}: winner ${m.winner}, ${m.board.turn} turns, out at ${outs.join(', ')}`);
  if (outs.length === 3 && Math.min(...outs) >= 80 && m.board.turn <= 400) {
    writeFileSync('src/lib/minpentai/watch-moves.ts', `/**
 * GENERATED by scripts/record-minpentai-match.ts. Do not edit.
 * The placements of the recorded four-player match (seed ${seed}): winner ${m.winner}, ${m.board.turn} turns.
 */
import type { Placement } from './match';

export const WATCH_MOVES: { seed: number; winner: number; turns: number; moves: { turn: number; player: number; p: Placement }[] } = ${JSON.stringify({ seed, winner: m.winner, turns: m.board.turn, moves })};
`);
    console.log(`kept seed ${seed}`);
    break;
  }
}
